# Generated by Django 4.0.1 on 2022-06-02 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('diseaseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cp', models.PositiveIntegerField()),
                ('trestbps', models.PositiveIntegerField()),
                ('chol', models.PositiveIntegerField()),
                ('fbs', models.PositiveIntegerField()),
                ('restecg', models.PositiveIntegerField()),
                ('thalach', models.PositiveIntegerField()),
                ('exang', models.PositiveIntegerField()),
                ('oldpeak', models.FloatField()),
                ('slope', models.PositiveIntegerField()),
                ('ca', models.PositiveIntegerField()),
                ('thal', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile')),
            ],
        ),
    ]
