# Generated by Django 4.0.1 on 2022-06-02 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diseasePrediction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartdisease',
            name='age',
        ),
        migrations.RemoveField(
            model_name='heartdisease',
            name='gender',
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
