# Generated by Django 4.0.1 on 2022-06-02 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diseasePrediction', '0002_remove_heartdisease_age_remove_heartdisease_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartdisease',
            old_name='diseaseID',
            new_name='heartDiseaseID',
        ),
        migrations.AddField(
            model_name='heartdisease',
            name='accuracy',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heartdisease',
            name='diseaseDetected',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartDiseasePatient', to=settings.AUTH_USER_MODEL),
        ),
    ]
