# Generated by Django 4.0.1 on 2022-06-05 18:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diseasePrediction', '0003_rename_diseaseid_heartdisease_heartdiseaseid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('diseasePredictionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('testNumber', models.IntegerField()),
                ('diseaseID', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiseasePredictionProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
