# Generated by Django 4.0.1 on 2022-06-12 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diseasePrediction', '0004_diseaseprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesDisease',
            fields=[
                ('diabetesDiseaseID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pregnancies', models.PositiveIntegerField()),
                ('glucose', models.PositiveIntegerField()),
                ('bloodPressure', models.PositiveIntegerField()),
                ('skinThickness', models.PositiveIntegerField()),
                ('insulin', models.PositiveIntegerField()),
                ('BMI', models.FloatField()),
                ('diabetesPedigreeFunction', models.FloatField()),
                ('diseaseDetected', models.IntegerField(default=-1)),
                ('accuracy', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetesDiseasePatient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
