# Generated by Django 3.2.8 on 2022-01-27 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_from', models.DateTimeField(blank=True, null=True)),
                ('monday_to', models.DateTimeField(blank=True, null=True)),
                ('tuesday_from', models.DateTimeField(blank=True, null=True)),
                ('tuesday_to', models.DateTimeField(blank=True, null=True)),
                ('wednesday_from', models.DateTimeField(blank=True, null=True)),
                ('wednesday_to', models.DateTimeField(blank=True, null=True)),
                ('thursday_from', models.DateTimeField(blank=True, null=True)),
                ('thursday_to', models.DateTimeField(blank=True, null=True)),
                ('friday_from', models.DateTimeField(blank=True, null=True)),
                ('friday_to', models.DateTimeField(blank=True, null=True)),
                ('saturday_from', models.DateTimeField(blank=True, null=True)),
                ('saturday_to', models.DateTimeField(blank=True, null=True)),
                ('sunday_from', models.DateTimeField(blank=True, null=True)),
                ('sunday_to', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('degree_name', models.CharField(max_length=200)),
                ('degree_date', models.DateField()),
                ('university', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('Did', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('available_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.availability')),
                ('qualifications', models.ManyToManyField(blank=True, to='doctors.Qualification')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
