# Generated by Django 3.2.8 on 2022-01-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20220131_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
