# Generated by Django 3.2.8 on 2022-01-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
