# Generated by Django 3.2.8 on 2022-02-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_availability_friday_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='availability',
            name='Did',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='Did',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.profile'),
            preserve_default=False,
        ),
    ]
