# Generated by Django 3.2.8 on 2022-02-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_auto_20220201_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='Did',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='Did',
            new_name='profile',
        ),
    ]
