# Generated by Django 3.2.8 on 2022-03-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_auto_20220201_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
