# Generated by Django 3.2.8 on 2022-03-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_delete_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='university',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='degree_name',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MS', 'MS')], default='', max_length=100),
        ),
    ]
