# Generated by Django 3.2.8 on 2022-04-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_alter_qualification_degree_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='university',
            field=models.CharField(max_length=400),
        ),
    ]
