# Generated by Django 3.2.8 on 2022-03-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_auto_20220331_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree_date',
            field=models.IntegerField(),
        ),
    ]
