# Generated by Django 3.2.8 on 2022-04-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_auto_20220422_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registrationNumber',
            field=models.IntegerField(null=True),
        ),
    ]
