# Generated by Django 3.2.8 on 2022-04-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_alter_profile_registrationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registrationNumber',
            field=models.IntegerField(),
        ),
    ]
