# Generated by Django 3.2.8 on 2022-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_auto_20220423_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stateMedicalCouncil',
            field=models.CharField(default='', max_length=300),
        ),
    ]
