# Generated by Django 3.2.8 on 2022-04-04 04:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0015_auto_20220404_0954'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('messageID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('messageBody', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('messageImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('clientProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientInConversation', to='clients.clientprofile')),
                ('doctorProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorInConversation', to='doctors.profile')),
            ],
        ),
    ]
