# Generated by Django 3.2.8 on 2022-04-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='isRead',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
