# Generated by Django 4.0.1 on 2022-04-12 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_auto_20220404_0954'),
        ('clients', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('appointmentLink', models.TextField()),
                ('appointmentPassword', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recieverProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecieverInConversation', to='clients.clientprofile')),
                ('senderProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SenderInConversation', to='doctors.profile')),
            ],
        ),
    ]
