# Generated by Django 4.0.1 on 2022-11-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_meeting_tempmeeting_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='appointmentLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
